/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neocoretechs_cublas_Gemm */

#ifndef _Included_com_neocoretechs_cublas_Gemm
#define _Included_com_neocoretechs_cublas_Gemm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    matrixDotProductD
 * Signature: (JII[DII[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductD
  (JNIEnv *, jclass, jlong, jint, jint, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    matrixDotProductDBatch
 * Signature: (JIILjava/util/ArrayList;IILjava/util/ArrayList;Ljava/util/ArrayList;I)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductDBatch
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jint, jint, jobject, jobject, jint);

/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    matrixDotProductDStream
 * Signature: (JIILjava/util/ArrayList;IILjava/util/ArrayList;Ljava/util/ArrayList;I)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductDStream
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jint, jint, jobject, jobject, jint);

/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    matrixDotProductDCPU
 * Signature: (II[DII[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductDCPU
  (JNIEnv *, jclass, jint, jint, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    matrixDotProductDCPUBatch
 * Signature: (IILjava/util/ArrayList;IILjava/util/ArrayList;Ljava/util/ArrayList;I)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductDCPUBatch
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint, jobject, jobject, jint);

/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    matrixDotProductF
 * Signature: (JII[FII[F[F)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductF
  (JNIEnv *, jclass, jlong, jint, jint, jfloatArray, jint, jint, jfloatArray, jfloatArray);

/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    matrixDotProductFBatch
 * Signature: (JIILjava/util/ArrayList;IILjava/util/ArrayList;Ljava/util/ArrayList;I)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductFBatch
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jint, jint, jobject, jobject, jint);

/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    matrixDotProductFStream
 * Signature: (JIILjava/util/ArrayList;IILjava/util/ArrayList;Ljava/util/ArrayList;I)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductFStream
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jint, jint, jobject, jobject, jint);

/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    matrixDotProductFCPU
 * Signature: (II[FII[F[F)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductFCPU
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint, jint, jfloatArray, jfloatArray);

/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    matrixDotProductFCPUBatch
 * Signature: (IILjava/util/ArrayList;IILjava/util/ArrayList;Ljava/util/ArrayList;I)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductFCPUBatch
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint, jobject, jobject, jint);

/*
* Class:     com_neocoretechs_cublas_Gemm
* Method : matrixDotProductF16
* Signature : (LII[DII[D[D)I
*/
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductF16
(JNIEnv * env, jclass clazz, jlong handle, jint rows1, jint columns1, jfloatArray m1, jint rows2, jint columns2, jfloatArray m2, jfloatArray mr);

/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    matrixDotProductF16Batch
 * Signature: (JIILjava/util/ArrayList;IILjava/util/ArrayList;Ljava/util/ArrayList;I)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductF16Batch
(JNIEnv* env, jclass clazz, jlong handle, jint rows1, jint columns1, jobject m1_AList, jint rows2, jint columns2, jobject m2_AList, jobject mr_AList, jint batchSize);

/*
* Class:  com_neocoretechs_cublas_Gemm
* Method: matrixDotProductF16StridedBatch
* Signature : (JIILjava/util/ArrayList;IILjava/util/ArrayList;Ljava/util/ArrayList;I)I
*/
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductF16StridedBatch
(JNIEnv * env, jclass clazz, jlong handle, jint rows1, jint columns1, jobject m1_AList, jint rows2, jint columns2, jobject m2_AList, jobject mr_AList, jint batchSize);

/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    matrixDotProductF16Stream
 * Signature: (JIILjava/util/ArrayList;IILjava/util/ArrayList;Ljava/util/ArrayList;I)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_matrixDotProductF16Stream
(JNIEnv* env, jclass clazz, jlong handle, jint rows1, jint columns1, jobject m1_AList, jint rows2, jint columns2, jobject m2_AList, jobject mr_AList, jint batchSize);

/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    cublasHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_neocoretechs_cublas_Gemm_cublasHandle
  (JNIEnv *, jclass);

/*
 * Class:     com_neocoretechs_cublas_Gemm
 * Method:    cublasHandleDestroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_cublas_Gemm_cublasHandleDestroy
  (JNIEnv *, jclass, jlong);

JNIEXPORT jlongArray JNICALL Java_com_neocoretechs_cublas_Gemm_cudaMemGetInfo(JNIEnv* env, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
