/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neocoretechs_neurovolve_MatrixCu */

#ifndef _Included_com_neocoretechs_neurovolve_MatrixCu
#define _Included_com_neocoretechs_neurovolve_MatrixCu
#ifdef __cplusplus
extern "C" {
#endif
#undef com_neocoretechs_neurovolve_MatrixCu_serialVersionUID
#define com_neocoretechs_neurovolve_MatrixCu_serialVersionUID -5112564161732998513i64
/*
 * Class:     com_neocoretechs_neurovolve_MatrixCu
 * Method:    matrixDotProductD
 * Signature: (II[DII[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_neocoretechs_neurovolve_Matrix_matrixDotProductD
  (JNIEnv *, jclass, jint, jint, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
